name: Blue Iris Books website
baseurl: https://bibpress.com
permalink: pretty
title: Blue Iris Books
description: Blue Iris Books is an independent publishing company. We publish novels, memoirs, essays, and poetry.
